version: '3'
services:
  node0:
    image: primihub/primihub-node:latest
    restart: "always"
    container_name: node2_primihub
    ports:
      - "8050:50050"
      - "10120:12120"
      - "10121:12121"
    volumes:
      - ./config:/app/config
      - ./data:/data

    extra_hosts:
      - "node0_primihub:172.28.1.10"
      - "node1_primihub:172.28.1.11"
      - "node2_primihub:172.28.1.12"
      
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50050  --node_id=node0 --config=/app/config/primihub_node0.yaml"
    networks:
      testing_net:
        ipv4_address: 172.28.1.10
    depends_on:
      - simple_bootstrap_node

  simple_bootstrap_node:
    image: primihub/simple-bootstrap-node:1.0 
    container_name: simple_bootstrap_node
    restart: "always"
    ports:
      - "4001:4001"
    entrypoint: 
      - "/app/simple-bootstrap-node"
    networks:
      testing_net:
        ipv4_address: 172.28.1.13

networks:
  testing_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16